# Generated by Django 5.2 on 2025-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_update_create_photo_post_photo_alter_post_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
